<?php

namespace AppBundle\Repository;

/**
 * CommentaireHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireHotelRepository extends \Doctrine\ORM\EntityRepository
{
}
