<?php

namespace AppBundle\Repository;

/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends \Doctrine\ORM\EntityRepository
{
}
